"ci/cd"

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -6,6 +6,7 @@ on:
     branches: [main]
   pull_request:
     branches: [main]
+  workflow_dispatch: {}
 
 jobs:
   build:
@@ -36,11 +37,16 @@ jobs:
       - name: Archive build files
         run: |
           echo "Archiving build files"
-          tar -czf build.tar.gz -C client build
-          echo "Contents of the current directory after archiving:"
-          ls -l
-          echo "Contents of the tar archive:"
-          tar -tzf build.tar.gz
+          if [ -d client/build ]; then
+            tar -czf build.tar.gz -C client build
+            echo "Contents of the current directory after archiving:"
+            ls -l
+            echo "Contents of the tar archive:"
+            tar -tzf build.tar.gz
+          else
+            echo "Error: client/build directory does not exist!"
+            exit 1
+          fi
 
   # CD
   deploy:
